<?php

/*
 * Implement hook help to provide help description for zregistration custom
 * module.
 */
function zregistration_help($path, $arg){
  switch ($path) {
    case "admin/help#zregistration":
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Z Registration is a module to understand about registration process.') . '</p>';
      return $output;
      break; 
  }
}

/*
 * Implement hook menu to customize quick access menu to module feature
 */
function zregistration_menu() {
    $items = array();
    
    $items['registration'] = array(
        'title' => 'Registered Users',
        'page callback' => 'zregistration_reg_page',
        'access arguments' => array('administer'),
    );
    
    $items['registration/generate_pdf/%'] = array(
        'title' => 'Student Information',
        'page callback' => 'zregistration_generate_pdf',
        'page arguments' => array(2),
        'access arguments' => array('administer'),
    );
    
    $items['registration/generate_excel'] = array(
        'title' => 'Student List',
        'page callback' => 'zregistration_generate_excel',
        'access arguments' => array('administer'),
    );
    
    return $items;
}

/*
 * Page callback function to see registered users
 */
function zregistration_reg_page(){
    $query = db_select('users_roles', 'ur')
            ->fields('ur', array('uid'))
            ->condition('rid', 5, '=')
            ->execute()
            ->fetchCol();
    
    $records = user_load_multiple($query);
    
    $header = array(
        array('data' => 'Username', 'field' => 'username'),
        'status' => 'Status',
        'operations' => 'Operations',
        'pdf' => 'Download Information',
    );
    
    $space = str_repeat('&nbsp', 2);
    $rows = array();
    foreach($records as $user) {
        $status = $user->status;
        if ($status == 1) {
            $str_status = 'active';
        } else {
            $str_status = 'blocked';
        }
        $rows[$user->uid] = array(
            'username' => l($user->name, 'user/' . $user->uid),
            'status' => $str_status,
            'operations' =>l('main profile', 'profile-main/' . $user->uid) . $space . l('student profile', 'profile-student_profile/' . $user->uid),
            'pdf' => l('here', 'registration/generate_pdf/' . $user->uid),
        );
    }
    
    $out = theme('table', array('header' => $header, 'rows' => $rows, 'caption' => l('Add student', 'admin/people/create') . $space . l('Get List', '/registration/generate_excel')));
    
    return $out;
}

/*
 * alter form to validate registration courses
 */
function zregistration_form_alter(&$form, &$form_state, $form_id){
    if($form_id == 'profile2_edit_student_profile_form'){
        $form['profile_student_profile']
                ['field_registration']['und'][0]['field_reg_courses']['und']
                ['#element_validate'][] = 'zregistration_courses_validate';
    }
}

/*
 * This function validate semester in academic year and also registration courses.
 */
function zregistration_courses_validate($form, &$form_state){
    // get registration info section
    $registration_sets = $form_state['input']['profile_student_profile']['field_registration']['und'];
    // check if more than 1 registration set (semester)
    if (sizeof($registration_sets) > 1){
        // variable to store all intersect courses ID
        $intersect = array();
        // variable to store all courses on iteration
        $combine_array = array();
        // variable to store all courses error msg
        $courses_error_msg = '';
        // variable to store both academic year and semester
        $acad_ym = array();
        // loop through registration info set
        foreach ($registration_sets as $info) {
            // make an array of both academic year and semester
            $a = array(0 => $info['field_reg_academic_year']['und'], 1 => $info['field_reg_semester']['und']);
            // if that array is in our all year-semester array or not
            if (!in_array($a, $acad_ym)){
                // if no, put it in main array
                array_push($acad_ym, $a);
            } else {
                // if yes, alert error
                form_set_error('acad_year_semester_error', 'You cannot register to same year and same semester.');
            }
            
            // get course ID
            $course_id = $info['field_reg_courses']['und'];
            // if the big array that store course ID is empty
            if (empty($combine_array)) {
                // put the first one to it
                $combine_array = $course_id;
            } else {
                // compare the main array and course id, and put the intersect course to intersect array
                $intersect += array_intersect($combine_array, $course_id);
                $combine_array = array_merge($combine_array, $course_id);
            }
        }
        
        // if there is at least 1 course ID intersect, alert msg with course name
        if (sizeof($intersect) > 0){
            $courses_name = taxonomy_term_load_multiple($intersect);
            foreach($courses_name as $name){
                $courses_error_msg .= $name->name . ' is already taken in previous semester.<br>';
            }
            form_set_error('retake_courses_error', $courses_error_msg);
        }
    }
}

function zregistration_generate_pdf($uid){
    $mpdf_path = libraries_get_path('mpdf');
    if ($mpdf_path != ''){
        require_once libraries_get_path('mpdf') . '/mpdf.php';
        // define value
        $profile = profile2_load_by_user($uid);
        
        $field_name = $profile['main']->field_full_name;
        $name = $field_name['und'][0]['value'];
        
        $field_gender = $profile['main']->field_reg_gender;
        $gender = $field_gender['und'][0]['value'];
        
        $field_dob = $profile['main']->field_reg_date_of_birth;
        $dob = date('d-m-Y', strtotime($field_dob['und'][0]['value']));
        
        $field_pob = $profile['main']->field_reg_place_of_birth;
        $pob = $field_pob['und'][0]['value'];
        
        $field_pschool = $profile['student_profile']->field_primary_school;
        $pschool = $field_pschool['und'][0]['value'];
        
        $field_eschool = $profile['student_profile']->field_elementary_school;
        $eschool = $field_eschool['und'][0]['value'];
        
        $field_hschool = $profile['student_profile']->field_high_school;
        $hschool = $field_hschool['und'][0]['value'];
        
        $field_major = $profile['student_profile']->field_department_pref1;
        $major_id = taxonomy_term_load($field_major['und'][0]['target_id']);
        $major = $major_id->name;
        
        // from here define the layout of form
        $html = '
            <h1 style="text-align: center;">Student Information</h1>
            <h3 style="background-color: #808080;">Section I: Student\'s Personal Details</h2>
            <table style="height: 200px; width: 815px;">
                <tbody>
                    <tr>
                        <td style="width: 385px;">Name</td>
                        <td style="width: 19px;">:</td>
                        <td style="width: 389px;">' . $name . '</td>
                    </tr>
                    <tr>
                        <td style="width: 385px;">Gender</td>
                        <td style="width: 19px;">:</td>
                        <td style="width: 389px;">' . $gender . '</td>
                    </tr>
                    <tr>
                        <td style="width: 385px;">Date of Birth</td>
                        <td style="width: 19px;">:</td>
                        <td style="width: 389px;">' . $dob . '</td>
                    </tr>
                    <tr>
                        <td style="width: 385px;">Place of Birth</td>
                        <td style="width: 19px;">:</td>
                        <td style="width: 389px;">' . $pob . '</td>
                    </tr>
                </tbody>
            </table>
            <h3 style="background-color: #808080;">Section II: Student\'s Educational Details</h2>
            <table style="height: 500px; width: 815px;">
                <tbody>
                    <tr>
                        <td style="width: 385px;">Primary School</td>
                        <td style="width: 19px;">:</td>
                        <td style="width: 389px;">' . $pschool . '</td>
                    </tr>
                    <tr>
                        <td style="width: 385px;">Elementary School</td>
                        <td style="width: 19px;">:</td>
                        <td style="width: 389px;">' . $eschool . '</td>
                    </tr>
                    <tr>
                        <td style="width: 385px;">High School</td>
                        <td style="width: 19px;">:</td>
                        <td style="width: 389px;">' . $hschool . '</td>
                    </tr>
                    <tr>
                        <td style="width: 385px;">Major</td>
                        <td style="width: 19px;">:</td>
                        <td style="width: 389px;">' . $major . '</td>
                    </tr>';
        $field_reg = $profile['student_profile']->field_registration;
        $reg_collection_id = array();
        foreach($field_reg['und'] as $reg){
            $reg_collection_id[] = $reg['value'];
        }
        
        $reg_collection = field_collection_item_load_multiple($reg_collection_id);
        $academic_ys = array();
        $semesters = array();
        $courses = array();
        foreach ($reg_collection as $val){
            $field_academic = $val->field_reg_academic_year;
            $academic_ys[] = $field_academic['und'][0]['value'];
            
            $field_semester = $val->field_reg_semester;
            $semesters[] = $field_semester['und'][0]['value'];
            
            $field_courses = $val->field_reg_courses;
            $courses[] = $field_courses['und'];
        }
        $academic = '';
        $semester = '';
        
        foreach ($courses as $key=>$val1){
            $academic = $academic_ys[$key];
            $semester = $semesters[$key];
            $html .= '<tr>
                        <td style="width: 385px;">Academic Year</td>
                        <td style="width: 19px;">:</td>
                        <td style="width: 389px;">' . $academic . '</td>
                    </tr>
                    <tr>
                        <td style="width: 385px;">Semester</td>
                        <td style="width: 19px;">:</td>
                        <td style="width: 389px;">' . $semester . '</td>
                    </tr>';
            $c = '';
            foreach ($val1 as $v){
                $a = taxonomy_term_load($v['target_id']);
                $d = $a->name;
                $c .= $d . '<br>';
            }
            $html .= '<tr>
                        <td style="width: 385px;">Courses</td>
                        <td style="width: 19px;">:</td>
                        <td style="width: 389px;">' . $c . '</td>
                    </tr>';
        }
        $html .= '
                </tbody>
            </table>';
    
        // from here generate the pdf
        $mpdf = new mPDF('c', 'A4');
        $mpdf->writeHTML($html);
        $mpdf->Output('student_info.pdf', 'I');
    } else {
        $out = array(
            '#markup' => 'mPDF does not exist.',
        );
        return $out;
    }
}

function zregistration_generate_excel(){
    $phpexcel_path = libraries_get_path('phpexcel');
    if($phpexcel_path == ''){
        require_once $phpexcel_path . '/Classes/PHPExcel.php';
        
        $excel = new PHPExcel();
        $excel->setActiveSheetIndex(0)
                ->setCellValue('A1', 'Registered Students List')
                ->setCellValue('A3', 'Name')
                ->setCellValue('B3', 'Gender')
                ->setCellValue('C3', 'Date of Birth')
                ->setCellValue('D3', 'Place of Birth')
                ->setCellValue('E3', 'Primary School')
                ->setCellValue('F3', 'Elementary School')
                ->setCellValue('G3', 'High School')
                ->setCellValue('H3', 'Department');
        
        $excel->getActiveSheet()->mergeCells('A1:H1');
        $excel->getActiveSheet()->getStyle('A1')->getAlignment()->setHorizontal('center');
        
        $row = 4;
        $query = db_select('users_roles', 'ur')
            ->fields('ur', array('uid'))
            ->condition('rid', 5, '=')
            ->execute()
            ->fetchCol();
        
        // define values
        foreach($query as $uid){
            $profile = profile2_load_by_user($uid);

            $field_name = $profile['main']->field_full_name;
            $name = $field_name['und'][0]['value'];

            $field_gender = $profile['main']->field_reg_gender;
            $gender = $field_gender['und'][0]['value'];

            $field_dob = $profile['main']->field_reg_date_of_birth;
            $dob = date('d-m-Y', strtotime($field_dob['und'][0]['value']));

            $field_pob = $profile['main']->field_reg_place_of_birth;
            $pob = $field_pob['und'][0]['value'];

            $field_pschool = $profile['student_profile']->field_primary_school;
            $pschool = $field_pschool['und'][0]['value'];

            $field_eschool = $profile['student_profile']->field_elementary_school;
            $eschool = $field_eschool['und'][0]['value'];

            $field_hschool = $profile['student_profile']->field_high_school;
            $hschool = $field_hschool['und'][0]['value'];

            $field_major = $profile['student_profile']->field_department_pref1;
            $major_id = taxonomy_term_load($field_major['und'][0]['target_id']);
            $major = $major_id->name;
            
            $excel->getActiveSheet()
                    ->setCellValue('A'.$row, $name)
                    ->setCellValue('B'.$row, $gender)
                    ->setCellValue('C'.$row, $dob)
                    ->setCellValue('D'.$row, $pob)
                    ->setCellValue('E'.$row, $pschool)
                    ->setCellValue('F'.$row, $eschool)
                    ->setCellValue('G'.$row, $hschool)
                    ->setCellValue('H'.$row, $major);
                    
            $row++;
        }
        
        foreach(range('A','H') as $columnID) {
            $excel->getActiveSheet()->getColumnDimension($columnID)
                    ->setAutoSize(true);
        }
        
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment;filename="students.xlsx"');
        header('Cache-Control: max-age=0');
        
        $file = PHPExcel_IOFactory::createWriter($excel, 'Excel2007');
        $file->save('php://output');
    } else {
        $out = array(
            '#markup' => 'PHPExcel does not exist.',
        );
        return $out;
    }
}

//SELECT users.uid AS uid FROM users LEFT JOIN profile ON users.uid = profile.uid AND (profile.type = 'student_profile') INNER JOIN users_roles ON users.uid = users_roles.uid WHERE (( (users_roles.rid = '5') AND( (CONCAT_WS(' ', users.name) LIKE '%n%') )))