<?php

/**
 * @file
 * A block module that displays recent blog and forum posts.
 */

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function current_posts_help($path, $arg){
  switch ($path) {
    case "admin/help#current_posts":
      return t("Displays links to nodes created on this date"); 
      break; 
  }
}

/**
 * Implements hook_menu().
 */
function current_posts_menu() {
  $items = array();

  $items['admin/config/content/current_posts'] = array(
    'title' => 'Current posts',
    'description' => 'Configuration for Current posts module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('current_posts_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );
  
  $items['current_posts'] = array(
    'title' => 'Current posts page',
    'page callback' => 'current_posts_page',
    'access arguments' => array('access content'),
  );
  
  $items['current_posts/form'] = array(
    'title' => 'Current posts form',
    'description' => 'A form to mess around with.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('current_posts_page_form'),
    'access arguments' => array('access content'),
    'access callback' => TRUE,
  );
  
  $items['results/%'] = array(
      'title' => 'Form Result',
      'page callback' => 'current_posts_results_page',
      'page arguments' => array(1),
      'access callback' => true,
  );
  
  $items['register'] = array(
      'title' => 'Application Form',
      'page callback' => 'register_page',
      'access arguments' => array('access content'),
  );
  
  $items['register/reg_form/%'] = array(
    'title' => 'Application Form',
    'description' => 'Entrance Exam Application Form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('current_posts_reg_form', 1, 2),
    'access arguments' => array('access content'),
    'access callback' => TRUE,
  );
  
  $items['applicant_info/%'] = array(
    'title' => 'Applicant Info',
    'page callback' => 'current_posts_applicant_info_page',
    'page arguments' => array(1),
    'access callback' => true,
  );
  
  $items['dept_form'] = array(
      'title' => 'Add new department',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('current_posts_dept_form'),
      'access arguments' => array('administer'),
      
  );
  
  $items['update_application_form'] = array(
      'title' => 'List Applicants',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('current_posts_update_application_form'),
      'access arguments' => array('administer'),
  );
  
  $items['student_list/autocomplete'] = array(
      'title' => 'Autocomplete for students',
      'page callback' => '_student_autocomplete',
      'access arguments' => array('administer'),
      'type' => MENU_CALLBACK,
  );
  
  $items['student_list/%'] = array(
      'title' => 'List Applicants',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('student_list_update_form', 1),
      'access arguments' => array('administer'),
  );
  
  $items['delete_acc/%'] = array(
      'title' => 'Delete Account',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('student_delete_form', 1),
      'access arguments' => array('administer'),
  );
  
  $items['current_posts/display_node'] = array(
      'title' => 'Display Node',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('current_posts_display_node'),
      'access arguments' => array('administer'),
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function current_posts_permission() {
  return array(
    'access current_posts content' => array(
      'title' => t('Access content for the Current posts module'),
    )
  );
}

/**
 * Custom content function. 
 * 
 * Set beginning and end dates, retrieve posts from database
 * saved in that time period.
 * 
 * @return 
 *   A result set of the targeted posts.
 */
function current_posts_contents(){
  //Get today's date.
  $today = getdate();
  //Calculate the date a week ago.
  $start_time = mktime(0, 0, 0,$today['mon'],($today['mday'] - 7), $today['year']);
  //Get all posts from one week ago to the present.
  $end_time = time();
  
  $max_num = variable_get('current_posts_max', 3);

//Use Database API to retrieve current posts.
  $query = db_select('node', 'n')
    ->fields('n', array('nid', 'title', 'created'))
    ->condition('status', 1) //Published.
    ->condition('created', array($start_time, $end_time), 'BETWEEN')
    ->orderBy('created', 'DESC') //Most recent first.
    ->range(0, $max_num)
    ->execute(); 
  return $query;  
}

/**
 * Implements hook_block_info().
 */
function current_posts_block_info() {
  $blocks['current_posts'] = array(
    // The name that will appear in the block list.
    'info' => t('Current posts'),
    // Default setting.
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 * 
 * Prepares the contents of the block.
 */
function current_posts_block_view($delta = '') {
  switch ($delta) {
    case 'current_posts':
      $block['subject'] = t('Current posts');
      if (user_access('access content')) {
        // Use our custom function to retrieve data.
        $result = current_posts_contents();
        // Array to contain items for the block to render.
        $items = array();
        // Iterate over the resultset and format as links.
        foreach ($result as $node) {
          $items[] = array(
            'data' => l($node->title, 'node/' . $node->nid),
          ); 
        }
       // No content in the last week.
        if (empty($items)) {
          $block['content'] = t('No posts available.');  
        } 
        else {
          // Pass data through theme function.
          $block['content'] = theme('item_list', array(
            'items' => $items));
        }
      }
    return $block;
  }
  
}

/**
 * Page callback: Current posts settings
 *
 * @see current_posts_menu()
 */
function current_posts_form($form, &$form_state) {
  $form['current_posts_max'] = array(
    '#type' => 'textfield',
    '#title' => t('Maximum number of posts'),
    '#default_value' => variable_get('current_posts_max', 3),
    '#size' => 2,
    '#maxlength' => 2,
    '#description' => t('The maximum number of links to display in the block.'),
    '#required' => true,
  );

  return system_settings_form($form);
}

/**
 * Implements validation from the Form API.
 * 
 * @param $form
 *   A structured array containing the elements and properties of the form.
 * @param $form_state
 *   An array that stores information about the form's current state 
 *   during processing.
 */
function current_posts_form_validate($form, &$form_state){
  $max_num = $form_state['values']['current_posts_max'];
  if (!is_numeric($max_num)){
    form_set_error('current_posts_max', t('You must enter a number for the maximum number of posts to display.'));
  }
  elseif ($max_num <= 0){
    form_set_error('current_posts_max', t('Maximum number of posts to display must be positive.'));
  }
}

/**
 * Page callback for /current_posts.
 */
function current_posts_page() {
  return t('Page Content');
}

/**
 * Page callback for /current_posts/form.
 */
function current_posts_page_form($form, &$form_state){
    if (empty($form_state['values']['current_posts_num'])){
        $type = array(0 => t('Instuctor'), 1 => t('Student'), 2 => t('Other'));
        
        $form['user_type'] = array(
          '#type' => 'radios',
          '#title' => t('User type'),
          '#default_value' => isset($node->type) ? $node->type : 0,
          '#options' => $type,
          '#description' => t('Select your position.'),
        );
        
        $form['current_posts_num'] = array(
            '#type' => 'textfield',
            '#title' => t('Maximum number of posts'),
            '#placeholder' => t('Enter number of posts'),
            '#description' => t('The maximum number of links to display in the block.'),
            '#required' => true,
        );
    
        $form['submit_button'] = array(
            '#type' => 'submit',
            '#value' => t('Click Here!'),
        );
    } else {
        $posts_num = $form_state['values']['current_posts_num'];
        $temp = '';
        for ($i = 0; $i < $posts_num; $i++) {
            $temp = $temp . 'Post index: ' . $i . '<br>';
        }
        
        $u_type_num = $form_state['values']['user_type'];
        $u_type = '';
        switch ($u_type_num) {
            case 0:
                $u_type = 'Your position is: Instuctor. <br>';
                break;
            case 1:
                $u_type = 'Your position is: Student. <br>';
                break;
            case 2:
                $u_type = 'Your position is: Other. <br>';
                break;
        }
        
        $form['submission'] = array(
            '#markup' => $u_type . $temp . t('You set max number of posts is: ' . $posts_num),
        );
    }
  
  return $form;
}

function current_posts_page_form_validate($form, &$form_state){
    $in = $form_state['values']['current_posts_num'];
    if (!is_numeric($in)){
        form_set_error('current_posts_num', t('Amount of posts to show must be number.'));
    } elseif ($in >= 100) {
        form_set_error('current_posts_num', t('Too much posts.'));
    } elseif ($in <=0) {
        form_set_error('current_posts_num', t('Number of posts must be positive.'));
    }
}

function current_posts_page_form_submit($form, &$form_state){
//    $form_state['rebuild'] = TRUE;
    $form_state['redirect'] = 'results/' . $form_state['values']['current_posts_num'] . '/' . $form_state['values']['user_type'];
}

function current_posts_results_page($var1, $var2) {
    $temp = '';
    for ($i = 0; $i < $var1; $i++) {
        $temp = $temp . 'Post index: ' . $i . '<br>';
    }
    
//    $u_type_num = $form_state['values']['user_type'];
    $u_type = '';
    switch ($var2) { 
        case 0:
            $u_type = 'Your position is: Instuctor. <br>';
            break;
        case 1:
            $u_type = 'Your position is: Student. <br>';
            break;
        case 2:
            $u_type = 'Your position is: Other. <br>';
            break;
    }
        
    $dis = array(
        '#markup' => $u_type . $temp . t('You set max number of posts is: ' . $var1),
    );
    
    return $dis;
//    return t('You set max number of posts is: ' . $var1);
}

/*
 * Example form: Registration application form
 */
function register_page(){
    header('Location: register/reg_form/0');
        $dis = array(
        '#markup' => '',
    );
        return $dis;
}

function current_posts_reg_form($form, &$form_state, $var1, $var2){
if (!isset($_SESSION['u_info']) || empty($_SESSION['u_info']) || $var2 == 0){
        $nid = 0;
        $fname = '';
        $name = '';
        $gender = 0;
        $dob = array('month' => 1, 'day' => 1, 'year' => 2000);
        $pob = '';
        $adr = '';
        $phone = '';
        $acad_year = '';
        $semester = 1;
        $major = 1;
    } 
//    elseif (isset($_SESSION['u_info'])) {
//        $nid = $_SESSION['u_info']['nid'];
//        $fname = $_SESSION['u_info']['family_name'];
//        $name = $_SESSION['u_info']['name'];
//        $gender = $_SESSION['u_info']['gender'];
//        $dob = array('month' => $_SESSION['u_info']['bmonth'],
//            'day' => $_SESSION['u_info']['bday'],
//            'year' => $_SESSION['u_info']['byear']);
//        $pob = $_SESSION['u_info']['pob'];
//        $adr = $_SESSION['u_info']['address'];
//        $phone = $_SESSION['u_info']['phone'];
//        $acad_year = $_SESSION['u_info']['acad_year'];
//        $semester = $_SESSION['u_info']['semester'];
//        $major = $_SESSION['u_info']['major_id'];
////        unset($_SESSION['u_info']);
//    }

    elseif ($_SESSION['u_info'] && is_numeric($var2) && $var2 != 0) {
        $usr = db_query("SELECT * FROM `user_info` WHERE `nid` = " . $var2)->fetchAssoc();
        $nid = $usr['nid'];
        $fname = $usr['family_name'];
        $name = $usr['name'];
        $gender = $usr['gender'];
        $dob = array('month' => $usr['bmonth'],
            'day' => $usr['bday'],
            'year' => $usr['byear']);
        $pob = $usr['pob'];
        $adr = $usr['address'];
        $phone = $usr['phone'];
        $acad_year = $usr['acad_year'];
        $semester = $usr['semester'];
        $major = $usr['major_id'];
//        unset($_SESSION['u_info']);
    }
    
//    debug($nid);
//    debug(!isset($_SESSION['u_info']) || empty($_SESSION['u_info']));
    $pref1 = array();
    $query = db_query("SELECT `nid`, `name`, `code` FROM `major`");
    $records = $query->fetchAll();
    foreach ($records as $record) {
        $pref1[$record->nid] = $record->name . ' (' . $record->code . ')';
    }
    
    $form['major'] = array(
        '#type' => 'value',
        '#value' => $pref1,
    );
    
    $form['nid'] = array(
        '#type' => 'hidden',
        '#value' => $nid,
    );
    
    $form['sect_1'] = array(
        '#type' => 'fieldset', 
        '#title' => t('Section 1 - Applicant\'s Personal Details'),
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
    );
    
    $form['sect_1']['reg_family_name'] = array(
        '#type' => 'textfield',
        '#title' => 'Family Name',
        '#default_value' => $fname,
        '#required' => true,
    );
    
    $form['sect_1']['reg_name'] = array(
        '#type' => 'textfield',
        '#title' => 'Name',
        '#default_value' => $name,
        '#required' => true,
    );
    
    $form['sect_1']['gender'] = array(
       '#type' => 'select',
       '#title' => t('Gender'),
       '#options' => array(
           0 => t('Female'),
           1 => t('Male'),
       ),
        '#default_value' => $gender,
       '#required' => true,
    );
    
    $form['sect_1']['dob'] = array(
        '#type' => 'date',
        '#title' => 'Date of Birth',
        '#default_value' => $dob,
        '#required' => true,
    );
    
    $form['sect_1']['pob'] = array(
        '#type' => 'textarea',
        '#title' => t('Place of Birth'),
        '#default_value' => $pob,
        '#resizable' => FALSE,
        '#required' => true,
    );
    
    $form['sect_1']['address'] = array(
        '#type' => 'textfield',
        '#title' => 'Address in Cambodia',
        '#default_value' => $adr,
    );
    
    $form['sect_1']['phone'] = array(
        '#type' => 'textfield',
        '#title' => 'Phone Number',
        '#default_value' => $phone,
        '#maxlength' => 10,
    );
    
    $form['sect_2'] = array(
        '#type' => 'fieldset', 
        '#title' => t('Section 2 - Applied Program'),
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
    );
    
    $form['sect_2']['academic_year'] = array(
        '#type' => 'select',
        '#title' => t('Academic Year'),
        '#options' => array(
           '2017-2018' => t('2017-2018'),
           '2016-2017' => t('2016-2017'),
           '2015-2016' => t('2015-2016'),
        ),
        '#default_value' => $acad_year,
        '#required' => true,
    );
    
    $form['sect_2']['semester'] = array(
        '#type' => 'radios',
        '#title' => 'Semester',
        '#options' => array(1 => 'Semester 1', 2 => 'Semester 2'),
        '#default_value' => $semester,
        '#required' => true,
    );
    
    $form['sect_2']['preference_1'] = array(
        '#type' => 'select',
        '#title' => 'First Preference',
        '#options' => $pref1,
        '#default_value' => $major,
        '#required' => true,
    );
    
    if ($nid == 0) {
        $sub_val = 'Submit';
        $func_call = array('submit_info');
        $check = 0;
    } else {
        $sub_val = 'Update';
        $func_call = array('update_info');
        $check = 1;
    }
    
    $form['agreement'] = array(
        '#type' => 'checkbox',
        '#title' => 'I agree with university rule and policy.',
        '#default_value' => $check,
        '#required' => true,
    );
    
    $form['submit_btn'] = array(
        '#type' => 'submit',
        '#value' => $sub_val,
        '#submit' => $func_call,
    );
//    } else {
//        $form = array(
//        '#markup' => 'Hello',
//    );
//    }
    
    return $form;
}

/*
 * Validating registration form
 */
function current_posts_reg_form_validate($form, &$form_state){
    $year_of_birth = $form_state['values']['dob']['year'];
    if ($year_of_birth && ($year_of_birth < 1900 || $year_of_birth > 2000)) {
      form_set_error('year_of_birth', t('Enter a year between 1900 and 2000.'));
    }
    
    $phone = $form_state['values']['phone'];
    if (!empty($phone) && !is_numeric($phone)){
        form_set_error('phone_number', t('Phone number must be number'));
    } elseif (!empty($phone) && is_numeric($phone) && strlen($phone) < 9) {
        form_set_error('phone_number', t('Phone number is not completed'));
    }
}

/*
 * Submitting form
 */
function submit_info($form, &$form_state){
    $_SESSION['form_values']['reg_form'] = $form_state['values'];
    $val = $_SESSION['form_values']['reg_form'];
//    debug($val);
    $form_state['redirect'] = 'applicant_info/' . $val['form_build_id'];
}

function update_info($form, &$form_state){
    $_SESSION['form_values']['reg_form'] = $form_state['values'];
    $val = $_SESSION['form_values']['reg_form'];
//    debug($val);
    $form_state['redirect'] = 'applicant_info/' . $val['form_build_id'];
}

function current_posts_applicant_info_page() {
    if (!isset($_SESSION)) {
        $dis = array(
        '#markup' => 'Please login.',
    );
    } elseif (empty($_SESSION['form_values'])) {
        header('Location: ..register/reg_form/0');
        $dis = array(
        '#markup' => '',
    );
    } else {
//        debug($_SESSION['form_values']);
    unset($_SESSION['u_info']);
    $nid = $_SESSION['form_values']['reg_form']['nid'];
    $name = $_SESSION['form_values']['reg_form']['reg_name'] . ' ' . $_SESSION['form_values']['reg_form']['reg_family_name'];
    $gender = $_SESSION['form_values']['reg_form']['gender'];
    $bmonth = $_SESSION['form_values']['reg_form']['dob']['month'];
    $bday = $_SESSION['form_values']['reg_form']['dob']['day'];
    $byear = $_SESSION['form_values']['reg_form']['dob']['year'];
    $pob = $_SESSION['form_values']['reg_form']['pob'];
    $address = $_SESSION['form_values']['reg_form']['address'];
    $phone = $_SESSION['form_values']['reg_form']['phone'];
    $acad_year = $_SESSION['form_values']['reg_form']['academic_year'];
    $semester = $_SESSION['form_values']['reg_form']['semester'];
    $major = $_SESSION['form_values']['reg_form']['preference_1'];
    
    if ($nid != 0) {
//    $query = db_query('UPDATE `user_info` SET '
//            . '`family_name`=\'' . $_SESSION['form_values']['reg_form']['reg_family_name'] . '\','
//            . '`name`=\'' . $_SESSION['form_values']['reg_form']['reg_name'] . '\','
//            . '`gender`=\'' . $gender . '\','
//            . '`bmonth`=\'' . $bmonth . '\','
//            . '`bday`=\'' . $bday . '\','
//            . '`byear`=\'' . $byear . '\','
//            . '`pob`=\'' . $pob . '\','
//            . '`address`=\'' . $address . '\','
//            . '`phone`=\'' . $phone . '\','
//            . '`acad_year`=\'' . $acad_year . '\','
//            . '`semester`=\'' . $semester . '\','
//            . '`major_id`=\'' . $major . '\' '
//            . 'WHERE `nid`=' . $nid);
        
        $query = db_update('user_info')
                ->fields(array(
                    'family_name' => $_SESSION['form_values']['reg_form']['reg_family_name'],
                    'name' => $_SESSION['form_values']['reg_form']['reg_name'],
                    'gender' => $gender,
                    'bmonth' => $bmonth,
                    'bday' => $bday,
                    'byear' => $byear,
                    'pob' => $pob,
                    'address' => $address,
                    'phone' => $phone,
                    'acad_year' => $acad_year,
                    'semester' => $semester,
                    'major_id' => $major,
                ))
                ->condition('nid', $nid, '=')
                ->execute();
        
        drupal_set_message('Updated complete');
    } else {
    
//    $query = db_query('INSERT INTO `user_info`(`family_name`, `name`, `gender`, `bmonth`, `bday`, `byear`, `pob`, `address`, `phone`, `acad_year`, `semester`, `major_id`) VALUES (\'' 
//            . $_SESSION['form_values']['reg_form']['reg_family_name'] . '\',\''
//            . $_SESSION['form_values']['reg_form']['reg_name'] . '\',\''
//            . $gender . '\',\''
//            . $bmonth . '\',\''
//            . $bday . '\',\''
//            . $byear . '\',\''
//            . $pob . '\',\''
//            . $address . '\',\''
//            . $phone . '\',\''
//            . $acad_year . '\',\''
//            . $semester . '\',\''
//            . $major
//            . '\')');
        
        $query = db_insert('user_info')
                ->fields(array(
                    'family_name' => $_SESSION['form_values']['reg_form']['reg_family_name'],
                    'name' => $_SESSION['form_values']['reg_form']['reg_name'],
                    'gender' => $gender,
                    'bmonth' => $bmonth,
                    'bday' => $bday,
                    'byear' => $byear,
                    'pob' => $pob,
                    'address' => $address,
                    'phone' => $phone,
                    'acad_year' => $acad_year,
                    'semester' => $semester,
                    'major_id' => $major,
                ))
                ->execute();
    
    drupal_set_message('Registered complete');
    }
    
    if ($gender == 0){
        $s_gender = 'F';
    } else {
        $s_gender = 'M';
    }
    
    $info = 'nid: ' . $nid . '<br>'
            . 'Name: ' . $name . '<br>'
            . 'Gender: ' . $s_gender . '<br>'
            . 'Date of Birth: ' . $bmonth . '-' . $bday . '-' . $byear . '<br>'
            . 'Place of Birth: ' . $pob . '<br>'
            . 'Address: ' . $address . '<br>'
            . 'Phone: ' . $phone . '<br>'
            . 'Academic Year: ' . $acad_year . '<br>'
            . 'Semester: ' . $semester . '<br>'
            . 'Major: ' . $_SESSION['form_values']['reg_form']['major'][$major] . '<br>'
            ;
    $dis = array(
        '#markup' => $info,
    );
    }
    return $dis;
}

function current_posts_dept_form($form, &$form_state){
    $form['dept_name'] = array(
        '#type' => 'textfield',
        '#title' => 'Department Name',
        '#maxlength' => 64,
        '#required' => true,
    );
    
    $form['dept_code'] = array(
        '#type' => 'textfield',
        '#title' => 'Department Code',
        '#maxlength' => 4,
        '#required' => true,
    );
    
    $form['dept_submit'] = array(
        '#type' => 'submit',
        '#value' => t('Submit'),
    );
    
    return $form;
}

function current_posts_dept_form_validate($form, &$form_state){
    
}

function current_posts_dept_form_submit($form, &$form_state){
    $d_name = $form_state['values']['dept_name'];
    $d_code = strtoupper($form_state['values']['dept_code']);
    
    $query = db_query('INSERT INTO `user_info`(`name`, `code`) VALUES (\'' . $d_name . '\',\'' . $d_code . '\')');
    
    drupal_set_message('Department added');
    
//    debug($d_name);
}

/*
 * autocomplete function for searching student
 * $string: student name
 */
function _student_autocomplete($string){
    $matches = array();
    $result = db_select('user_info', 'u')
            ->fields('u', array('family_name', 'name'))
            ->condition('name', '%' . db_like($string) . '%', 'LIKE')
            ->execute();
    
    foreach ($result as $row){
        $matches[$row->name] = check_plain($row->name . ' ' .$row->family_name);
    }
    
    drupal_json_output($matches);
}

function current_posts_update_application_form($form, &$form_state) {
    $form['search'] = array(
        '#type' => 'textfield',
        '#title' => 'Search applicant name',
        '#required' => true,
        '#autocomplete_path' => 'student_list/autocomplete',
    );
    
    $form['bnt_search'] = array(
        '#type' => 'submit',
        '#value' => 'Search',
    );
    
    $query = db_query("SELECT `nid`, `family_name`, `name`, `gender`, `bmonth`, `bday`, `byear` FROM `user_info`");
    $numRow = $query->rowCount();
//    $records = $usr->fetchAssoc();
//    debug($numRow);
    
    for ($i = 0; $i < $numRow; $i++) {
            $records[$i] = $query->fetchAssoc();
//            $path = $path . $records[$i]['nid'] . '_';
        }
//        debug($records);
    $header = array(
        'family_name' => t('First Name'),
        'name' => t('Last Name'),
        'gender' => t('Gender'),
        'dob' => t('Date of Birth'),
        'update' => t('Update'),
        'delete' => t('Delete'),
    );

    $options = array();
    foreach($records as $user){
        if($user['gender'] == 0){
            $str_gender = 'F';
        } elseif ($user['gender'] == 1) {
            $str_gender = 'M';
        }

        $options[$user['nid']] = array (
            'family_name' => $user['family_name'],
            'name' => $user['name'],
            'gender' => $str_gender,
            'dob' => $user['bmonth'] . '-' . $user['bday'] . '-' . $user['byear'],
            'update' => l('Update', 'register/reg_form/' . $user['nid']),
            'delete' => l('Delete', 'delete_acc/' . $user['nid']),
        );
    }
    
    $_SESSION['u_info'] = TRUE;

    $form['add_new'] = array(
        '#markup' => '<br>' . l('Add new applicant', 'register/reg_form/0'),
    );
    
    $form['table1'] = array(
        '#theme' => 'table',
//        '#caption' => l('Add new applicant', 'register/reg_form/0'),
        '#header' => $header,
        '#rows' =>$options,
    );
    
    return $form;
}

function current_posts_update_application_form_validate($form, &$form_state){
    
}

function current_posts_update_application_form_submit($form, &$form_state){
    $search = $form_state['values']['search'];
    $db_or = db_or()
            ->condition('name', '%' . $search . '%', 'LIKE')
            ->condition('family_name', '%' . $search . '%', 'LIKE');
    $query = db_select('user_info', 'u')
            ->fields('u', array('nid'))
            ->condition($db_or)
            ->execute()->fetchAll();
    $numRow = count($query);
    $path = '';
    if ($numRow == 0) {
        form_set_error('not found', t('Not found, please provide student full name'));
    } else {
        for ($i = 0; $i < $numRow; $i++) {
            $records[$i] = $query[$i]->nid;
            $path = $path . $records[$i] . '_';
        }
//        debug($path);
//        $_SESSION['u_info'] = TRUE;
        $form_state['redirect'] = 'student_list/' . $path;
    }
}

function student_list_update_form($form, &$form_state, $var1) {
    
//    debug($var1);
    $id = explode("_", $var1);
//    debug($id[0]);
    $usr = array();
    $records = array();
    for ($i = 0; $i < sizeof($id) - 1; $i++){
//        debug($id[$i]);
        $usr[$i] = db_query("SELECT `nid`, `family_name`, `name`, `gender`, `bmonth`, `bday`, `byear` FROM `user_info` WHERE `nid` = " . $id[$i]);
        $records[$i] = $usr[$i]->fetchAssoc();
    }
    
//    debug($records);
    
//    $users = array
//  (
//    array('uid' => 1, 'first_name' => 'Indy', 'last_name' => 'Jones'),
//    array('uid' => 2, 'first_name' => 'Darth', 'last_name' => 'Vader'),
//    array('uid' => 3, 'first_name' => 'Super', 'last_name' => 'Man'),
//  );
 
    $header = array(
        'family_name' => t('First Name'),
        'name' => t('Last Name'),
        'gender' => t('Gender'),
        'dob' => t('Date of Birth'),
        'update' => t('Update'),
        'delete' => t('Delete'),
    );

    $options = array();
    foreach($records as $user){
        if($user['gender'] == 0){
            $str_gender = 'F';
        } elseif ($user['gender'] == 1) {
            $str_gender = 'M';
        }

        $options[$user['nid']] = array (
            'family_name' => $user['family_name'],
            'name' => $user['name'],
            'gender' => $str_gender,
            'dob' => $user['bmonth'] . '-' . $user['bday'] . '-' . $user['byear'],
            'update' => l('Update', 'register/reg_form/' . $user['nid']),
            'delete' => l('Delete', 'delete_acc/' . $user['nid']),
        );
    }

    $form['table1'] = array(
        '#theme' => 'table',
        '#header' => $header,
        '#rows' =>$options,
    );
    
    return $form;
}

function student_delete_form($form, &$form_state, $var1) {
    $usr = db_query("SELECT `family_name`, `name` FROM `user_info` WHERE `nid` = " . $var1);
    $record = $usr->fetchAssoc();
//    debug($var1);
    $path = '/update_application_form';
    
    $form['nid'] = array(
        '#type' => 'hidden',
        '#value' => $var1,
    );
    
    return confirm_form($form, $question='Do you really want delete ' . $record['name'] . ' ' . $record['family_name'] . '? <br>', $path, $description = "Warning, this is the last step before form gets submitted.", $yes = "Delete");
//    return $form;
}

function student_delete_form_submit($form, &$form_state){
//    debug($form_state['values']);
    $query = db_delete('user_info');
    $query->condition('nid', $form_state['values']['nid']);
    $success = $query->execute();
    if ($success) {
        // Do something.
//        drupal_set_message('Application deleted');
        $form_state['redirect'] = '/update_application_form';
    } else {
        form_set_error('delete', t('Error occurs during process'));
    }
    //    $q = db_query("DELETE FROM `user_info` WHERE `nid` = " . $form_state['values']['nid']);
}

function current_posts_display_node(){
    $query = db_select('node', 'n')
            ->fields('n', array('nid'))
            ->orderBy('nid', 'ASC')
            ->execute()
            ->fetchAll();
    $count = count($query);
//    debug($count);
//    debug($query, 0, 1);
    for ($i = 0; $i < $count; $i++){
        
    }
    debug(node_load(11), 0, 1);
    
    $header = array(
        'family_name' => t('Title'),
        'name' => t('Type'),
        'gender' => t('Author'),
        'dob' => t('Status'),
        'update' => t('Updated'),
        'delete' => t('Operations'),
    );
    
    $options = array();
    
    $form['table1'] = array(
        '#theme' => 'table',
        '#header' => $header,
        '#rows' =>$options,
    );
    
    return $form;
}